spring:
  application:
    name: cardstore
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
  docker:
    compose:
      file: "../compose.yaml"


server:
  port: 8081

  